/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareBindings src/worker-configuration.d.ts` (hash: f11fb8bb9d1979ca42c156184c155c80)
interface __BaseEnv_CloudflareBindings {
	RAW_SNAPSHOTS: R2Bucket;
	DB: D1Database;
	JOBS: Queue;
	APP_ENV: "development";
	PUBLIC_ORIGIN: "http://localhost:4321";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ENV" | "PUBLIC_ORIGIN">> {}
}
