/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareBindings src/worker-configuration.d.ts` (hash: b58f9516558a273644d291c4bd927217)
interface __BaseEnv_CloudflareBindings {
	RAW_SNAPSHOTS: R2Bucket;
	DB: D1Database;
	JOBS: Queue;
	APP_ENV: "production";
	TABROOM_COLLECTION_MODE: "signed-runner";
	PUBLIC_ORIGIN: "https://national-points-race.pages.dev";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ENV" | "TABROOM_COLLECTION_MODE" | "PUBLIC_ORIGIN">> {}
}
